#!/usr/bin/env bash
#
# 在 Zimbra 主 nginx 的 443 server 块里注入一条 location /zimport-tools/
# 反代 127.0.0.1:8088。这样:
#   - Zimbra Web 内置 zimlet 的 iframe(同源 /zimport-tools/)能加载到应用
#   - 用户直接访问 https://<zimbra-host>/zimport-tools/ 也能用
#
# 实现:
#   1. 写一个 include 块到 /opt/zimbra/conf/nginx/includes/
#      nginx.conf.zimport-tools-main(包含 location)
#   2. 在 /opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template
#      的主 server 块末尾插入一行 include(首次会备份原版到 .bak.orig)
#   3. `zmproxyctl restart` 让 nginx 加载
#
# 重跑无害(幂等)。
#
# 用法:  bash setup-proxy.sh
set -euo pipefail

log()  { printf '\033[1;32m[proxy]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }

[ "$(id -u)" -eq 0 ] || { err "请用 root 运行"; exit 1; }
[ -x /opt/zimbra/bin/zmproxyctl ] || {
    err "未检测到 Zimbra (/opt/zimbra/bin/zmproxyctl 不存在);此脚本只能在 Zimbra 同机部署"
    exit 1
}

INC=/opt/zimbra/conf/nginx/includes/nginx.conf.zimport-tools-main
TMPL=/opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template

# --- 1. 写 location include 块 ---------------------------------------
log "写 $INC"
cat > "$INC" <<'NGINX'
# ZImport-tools sub-path inside Zimbra main 443 server.
# Generated by deploy/setup-proxy.sh. Re-run safely.
location ^~ /zimport-tools/ {
    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_pass http://127.0.0.1:8088/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
}
NGINX
chown zimbra:zimbra "$INC"
chmod 640 "$INC"

# --- 2. 备份 template(只首次) ---------------------------------------
if [ ! -f "${TMPL}.bak.orig" ]; then
    cp "$TMPL" "${TMPL}.bak.orig"
    log "已备份原始 template -> ${TMPL}.bak.orig"
fi

# --- 3. 在主 server 块末尾插入 include 行(幂等) ----------------------
log "确保 template 主 server 块包含 include 钩子"
# 用 setup.sh 装的 python3.11(CentOS 7 上没有 'python3' 这个命令)
PYBIN=/usr/local/bin/python3.11
[ -x "$PYBIN" ] || PYBIN=$(command -v python3 || true)
[ -x "$PYBIN" ] || { err "找不到 python3.11 或 python3"; exit 1; }
"$PYBIN" - <<PYEOF
p = "$TMPL"
inc_line = "    include /opt/zimbra/conf/nginx/includes/nginx.conf.zimport-tools-main;"
with open(p) as f:
    text = f.read()
if "nginx.conf.zimport-tools-main" in text:
    print("  template 已包含 include 行,跳过")
else:
    lines = text.splitlines(True)
    # 第一个独立 } 行 = 主 server 块结尾
    for i, line in enumerate(lines):
        if line.rstrip() == "}":
            lines.insert(i, inc_line + "\n")
            break
    with open(p, "w") as f:
        f.writelines(lines)
    print("  已插入 include 行")
PYEOF

# --- 4. 重启 zmproxy ---------------------------------------------------
log "重启 zmproxy 让配置生效(短暂中断 Zimbra webmail 代理)"
su - zimbra -c "zmproxyctl restart" | tail -5

# --- 5. 验证 -----------------------------------------------------------
log "验证 /zimport-tools/ 可达"
sleep 1
code=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 5 \
       "https://127.0.0.1/zimport-tools/")
log "  curl https://127.0.0.1/zimport-tools/  -> HTTP $code"
if [ "$code" != "200" ] && [ "$code" != "302" ]; then
    err "代理通了但回源非 200/302,检查 zimport-tools-web 是否在跑"
    exit 1
fi

log "反代配置完成。"
echo "  用户入口:Zimbra Web 左下角 Zimlets 面板的「数据导入」(zmzimletctl 已部署)"
echo "  直接访问:https://<zimbra-host>/zimport-tools/"
