#!/usr/bin/env bash
#
# Zimbra nginx 反向代理脚本 —— 在同机 Zimbra 上,把外部 https://host:PORT
# 反代到 ZImport 的 127.0.0.1:8088。复用 Zimbra 的现有证书。
#
# 通过两步实现:
#   1. 写一个独立 server 块到 /opt/zimbra/conf/nginx/includes/nginx.conf.zimport-tools
#   2. 在 /opt/zimbra/conf/nginx/templates/nginx.conf.web.template 末尾加一行
#      include,使 zmproxyctl restart 后 nginx 把它一并加载
#
# 重跑无害(幂等)。
#
# 用法:
#   bash setup-proxy.sh                # 默认 29443
#   bash setup-proxy.sh --port 9443    # 自定义端口
set -euo pipefail

PORT=29443

while [ $# -gt 0 ]; do
    case "$1" in
        --port) PORT="$2"; shift 2 ;;
        -h|--help)
            echo "用法: $0 [--port N]"; exit 0 ;;
        *) echo "未知参数: $1" >&2; exit 1 ;;
    esac
done

log()  { printf '\033[1;32m[proxy]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }

[ "$(id -u)" -eq 0 ] || { err "请用 root 运行"; exit 1; }
[ -x /opt/zimbra/bin/zmproxyctl ] || { err "未检测到 Zimbra (/opt/zimbra/bin/zmproxyctl 不存在),此脚本只用于 Zimbra 同机部署"; exit 1; }

ZIMBRA_HOST=$(su - zimbra -c "zmhostname" 2>/dev/null | head -1 | tr -d '[:space:]')

INC=/opt/zimbra/conf/nginx/includes/nginx.conf.zimport-tools
TMPL=/opt/zimbra/conf/nginx/templates/nginx.conf.web.template

log "目标端口: $PORT, server_name: $ZIMBRA_HOST"

# 1. 备份模板(只在首次备份)
if [ ! -f "${TMPL}.bak.orig" ]; then
    cp "$TMPL" "${TMPL}.bak.orig"
    log "已备份原始 template -> ${TMPL}.bak.orig"
fi

# 2. 写 server 块
log "写 $INC"
cat > "$INC" <<NGINX
# ZImport reverse proxy - generated by deploy/setup-proxy.sh
server {
    listen ${PORT} ssl;
    server_name ${ZIMBRA_HOST};

    ssl_certificate     /opt/zimbra/conf/nginx.crt;
    ssl_certificate_key /opt/zimbra/conf/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:zimport_ssl:5m;
    ssl_session_timeout 10m;

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

    access_log /opt/zimbra/log/nginx.access.log;
    error_log  /opt/zimbra/log/nginx.log;

    location / {
        proxy_pass http://127.0.0.1:8088;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
NGINX
chown zimbra:zimbra "$INC"
chmod 640 "$INC"

# 3. 在 template 末尾的 } 之前插入 include 行(幂等)
log "确保 template 包含 include 钩子"
python3 - <<PYEOF
p = "$TMPL"
with open(p) as f:
    text = f.read()
needle = "include /opt/zimbra/conf/nginx/includes/nginx.conf.zimport-tools;"
if needle in text:
    print("  template 已包含 include 行,跳过")
else:
    lines = text.splitlines(True)
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == "}":
            lines.insert(i, "    " + needle + "\n")
            break
    with open(p, "w") as f:
        f.writelines(lines)
    print("  已插入 include 行")
PYEOF

# 4. zmproxyctl restart
log "重启 zmproxy 让配置生效(短暂中断 Zimbra webmail 代理)"
su - zimbra -c "zmproxyctl restart" | tail -5

# 5. 验证监听
log "验证 ${PORT} 监听 + 本机访问"
sleep 1
if ss -tlnp 2>/dev/null | grep -q ":${PORT}\b"; then
    log "  ${PORT} 已监听"
else
    err "${PORT} 未监听,看 /opt/zimbra/log/nginx.log 排查"
    exit 1
fi
code=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 5 "https://127.0.0.1:${PORT}/")
log "  curl https://127.0.0.1:${PORT}/  -> HTTP ${code}"
if [ "$code" != "200" ] && [ "$code" != "302" ]; then
    err "代理通了但回源非 200/302,检查 zimport-tools-web 是否在跑"
    exit 1
fi

log "反代配置完成,访问 https://${ZIMBRA_HOST}:${PORT}/"
